project_name: simple-mutating-webhook
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/simple-mutating-webhook/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: simple-mutating-webhook
dockers:
  - image_templates:
      - phh129/{{ .ProjectName }}:{{ .ShortCommit }}
    dockerfile: GoReleaserDockerfile
release:
  disable: true
#announce:
#  slack:
#    enabled: true
#    message_template: '{{ .ProjectName }} dev successfully build & push!\n result image url : phh129/{{ .ProjectName }}:{{ .ShortCommit }}'
#    channel: '#your-channel'
#    username: 'simple-mutating-webhook-dev-release'
#    icon_url: 'https://goreleaser.com/static/logo.png'
