apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test
  labels:
    app: test-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "400m"
        ports:
          - containerPort: 8080