apiVersion: v1
kind: Service
metadata:
  name: simple-mutating-webhook
  namespace: simple-mutating-webhook
spec:
  selector:
    app: simple-mutating-webhook
  ports:
    - port: 443
      targetPort: gin